/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectOverviewRouteImport } from './routes/_authenticated/project-overview'
import { Route as AuthenticatedProjectBoardRouteImport } from './routes/_authenticated/project-board'
import { Route as AuthenticatedProcessWorkspaceRouteImport } from './routes/_authenticated/process-workspace'
import { Route as AuthenticatedPheromoneRouteImport } from './routes/_authenticated/pheromone'
import { Route as AuthenticatedOpenclawRouteImport } from './routes/_authenticated/openclaw'
import { Route as AuthenticatedOmegaRouteImport } from './routes/_authenticated/omega'
import { Route as AuthenticatedObsidianRouteImport } from './routes/_authenticated/obsidian'
import { Route as AuthenticatedObservabilityRouteImport } from './routes/_authenticated/observability'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedInventorRouteImport } from './routes/_authenticated/inventor'
import { Route as AuthenticatedFlywheelRouteImport } from './routes/_authenticated/flywheel'
import { Route as AuthenticatedFleetLearningRouteImport } from './routes/_authenticated/fleet-learning'
import { Route as AuthenticatedEngagementWorkspaceRouteImport } from './routes/_authenticated/engagement-workspace'
import { Route as AuthenticatedCronRouteImport } from './routes/_authenticated/cron'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedCognitiveRouteImport } from './routes/_authenticated/cognitive'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChainsRouteImport } from './routes/_authenticated/chains'
import { Route as AuthenticatedBenchmarkRouteImport } from './routes/_authenticated/benchmark'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnomalyRouteImport } from './routes/_authenticated/anomaly'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAdoptionRouteImport } from './routes/_authenticated/adoption'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings/activity'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedDeliverableDraftRouteImport } from './routes/_authenticated/deliverable/draft'
import { Route as AuthenticatedComplianceAuditRouteImport } from './routes/_authenticated/compliance/audit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectOverviewRoute =
  AuthenticatedProjectOverviewRouteImport.update({
    id: '/project-overview',
    path: '/project-overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectBoardRoute =
  AuthenticatedProjectBoardRouteImport.update({
    id: '/project-board',
    path: '/project-board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessWorkspaceRoute =
  AuthenticatedProcessWorkspaceRouteImport.update({
    id: '/process-workspace',
    path: '/process-workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPheromoneRoute = AuthenticatedPheromoneRouteImport.update({
  id: '/pheromone',
  path: '/pheromone',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpenclawRoute = AuthenticatedOpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOmegaRoute = AuthenticatedOmegaRouteImport.update({
  id: '/omega',
  path: '/omega',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObsidianRoute = AuthenticatedObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObservabilityRoute =
  AuthenticatedObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventorRoute = AuthenticatedInventorRouteImport.update({
  id: '/inventor',
  path: '/inventor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlywheelRoute = AuthenticatedFlywheelRouteImport.update({
  id: '/flywheel',
  path: '/flywheel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetLearningRoute =
  AuthenticatedFleetLearningRouteImport.update({
    id: '/fleet-learning',
    path: '/fleet-learning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngagementWorkspaceRoute =
  AuthenticatedEngagementWorkspaceRouteImport.update({
    id: '/engagement-workspace',
    path: '/engagement-workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCronRoute = AuthenticatedCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCognitiveRoute = AuthenticatedCognitiveRouteImport.update({
  id: '/cognitive',
  path: '/cognitive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChainsRoute = AuthenticatedChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBenchmarkRoute = AuthenticatedBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnomalyRoute = AuthenticatedAnomalyRouteImport.update({
  id: '/anomaly',
  path: '/anomaly',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdoptionRoute = AuthenticatedAdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDeliverableDraftRoute =
  AuthenticatedDeliverableDraftRouteImport.update({
    id: '/deliverable/draft',
    path: '/deliverable/draft',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceAuditRoute =
  AuthenticatedComplianceAuditRouteImport.update({
    id: '/compliance/audit',
    path: '/compliance/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/adoption': typeof AuthenticatedAdoptionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/anomaly': typeof AuthenticatedAnomalyRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/chains': typeof AuthenticatedChainsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cognitive': typeof AuthenticatedCognitiveRoute
  '/cost': typeof AuthenticatedCostRoute
  '/cron': typeof AuthenticatedCronRoute
  '/engagement-workspace': typeof AuthenticatedEngagementWorkspaceRoute
  '/fleet-learning': typeof AuthenticatedFleetLearningRoute
  '/flywheel': typeof AuthenticatedFlywheelRoute
  '/inventor': typeof AuthenticatedInventorRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/obsidian': typeof AuthenticatedObsidianRoute
  '/omega': typeof AuthenticatedOmegaRoute
  '/openclaw': typeof AuthenticatedOpenclawRoute
  '/pheromone': typeof AuthenticatedPheromoneRoute
  '/process-workspace': typeof AuthenticatedProcessWorkspaceRoute
  '/project-board': typeof AuthenticatedProjectBoardRoute
  '/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/compliance/audit': typeof AuthenticatedComplianceAuditRoute
  '/deliverable/draft': typeof AuthenticatedDeliverableDraftRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/adoption': typeof AuthenticatedAdoptionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/anomaly': typeof AuthenticatedAnomalyRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/chains': typeof AuthenticatedChainsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cognitive': typeof AuthenticatedCognitiveRoute
  '/cost': typeof AuthenticatedCostRoute
  '/cron': typeof AuthenticatedCronRoute
  '/engagement-workspace': typeof AuthenticatedEngagementWorkspaceRoute
  '/fleet-learning': typeof AuthenticatedFleetLearningRoute
  '/flywheel': typeof AuthenticatedFlywheelRoute
  '/inventor': typeof AuthenticatedInventorRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/obsidian': typeof AuthenticatedObsidianRoute
  '/omega': typeof AuthenticatedOmegaRoute
  '/openclaw': typeof AuthenticatedOpenclawRoute
  '/pheromone': typeof AuthenticatedPheromoneRoute
  '/process-workspace': typeof AuthenticatedProcessWorkspaceRoute
  '/project-board': typeof AuthenticatedProjectBoardRoute
  '/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/compliance/audit': typeof AuthenticatedComplianceAuditRoute
  '/deliverable/draft': typeof AuthenticatedDeliverableDraftRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/adoption': typeof AuthenticatedAdoptionRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/anomaly': typeof AuthenticatedAnomalyRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/benchmark': typeof AuthenticatedBenchmarkRoute
  '/_authenticated/chains': typeof AuthenticatedChainsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cognitive': typeof AuthenticatedCognitiveRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/cron': typeof AuthenticatedCronRoute
  '/_authenticated/engagement-workspace': typeof AuthenticatedEngagementWorkspaceRoute
  '/_authenticated/fleet-learning': typeof AuthenticatedFleetLearningRoute
  '/_authenticated/flywheel': typeof AuthenticatedFlywheelRoute
  '/_authenticated/inventor': typeof AuthenticatedInventorRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/observability': typeof AuthenticatedObservabilityRoute
  '/_authenticated/obsidian': typeof AuthenticatedObsidianRoute
  '/_authenticated/omega': typeof AuthenticatedOmegaRoute
  '/_authenticated/openclaw': typeof AuthenticatedOpenclawRoute
  '/_authenticated/pheromone': typeof AuthenticatedPheromoneRoute
  '/_authenticated/process-workspace': typeof AuthenticatedProcessWorkspaceRoute
  '/_authenticated/project-board': typeof AuthenticatedProjectBoardRoute
  '/_authenticated/project-overview': typeof AuthenticatedProjectOverviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/compliance/audit': typeof AuthenticatedComplianceAuditRoute
  '/_authenticated/deliverable/draft': typeof AuthenticatedDeliverableDraftRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/adoption'
    | '/agents'
    | '/anomaly'
    | '/audit'
    | '/benchmark'
    | '/chains'
    | '/chat'
    | '/cognitive'
    | '/cost'
    | '/cron'
    | '/engagement-workspace'
    | '/fleet-learning'
    | '/flywheel'
    | '/inventor'
    | '/knowledge'
    | '/observability'
    | '/obsidian'
    | '/omega'
    | '/openclaw'
    | '/pheromone'
    | '/process-workspace'
    | '/project-board'
    | '/project-overview'
    | '/settings'
    | '/compliance/audit'
    | '/deliverable/draft'
    | '/settings/account'
    | '/settings/activity'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/adoption'
    | '/agents'
    | '/anomaly'
    | '/audit'
    | '/benchmark'
    | '/chains'
    | '/chat'
    | '/cognitive'
    | '/cost'
    | '/cron'
    | '/engagement-workspace'
    | '/fleet-learning'
    | '/flywheel'
    | '/inventor'
    | '/knowledge'
    | '/observability'
    | '/obsidian'
    | '/omega'
    | '/openclaw'
    | '/pheromone'
    | '/process-workspace'
    | '/project-board'
    | '/project-overview'
    | '/settings'
    | '/'
    | '/compliance/audit'
    | '/deliverable/draft'
    | '/settings/account'
    | '/settings/activity'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/adoption'
    | '/_authenticated/agents'
    | '/_authenticated/anomaly'
    | '/_authenticated/audit'
    | '/_authenticated/benchmark'
    | '/_authenticated/chains'
    | '/_authenticated/chat'
    | '/_authenticated/cognitive'
    | '/_authenticated/cost'
    | '/_authenticated/cron'
    | '/_authenticated/engagement-workspace'
    | '/_authenticated/fleet-learning'
    | '/_authenticated/flywheel'
    | '/_authenticated/inventor'
    | '/_authenticated/knowledge'
    | '/_authenticated/observability'
    | '/_authenticated/obsidian'
    | '/_authenticated/omega'
    | '/_authenticated/openclaw'
    | '/_authenticated/pheromone'
    | '/_authenticated/process-workspace'
    | '/_authenticated/project-board'
    | '/_authenticated/project-overview'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/compliance/audit'
    | '/_authenticated/deliverable/draft'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/activity'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/integrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-overview': {
      id: '/_authenticated/project-overview'
      path: '/project-overview'
      fullPath: '/project-overview'
      preLoaderRoute: typeof AuthenticatedProjectOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-board': {
      id: '/_authenticated/project-board'
      path: '/project-board'
      fullPath: '/project-board'
      preLoaderRoute: typeof AuthenticatedProjectBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/process-workspace': {
      id: '/_authenticated/process-workspace'
      path: '/process-workspace'
      fullPath: '/process-workspace'
      preLoaderRoute: typeof AuthenticatedProcessWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pheromone': {
      id: '/_authenticated/pheromone'
      path: '/pheromone'
      fullPath: '/pheromone'
      preLoaderRoute: typeof AuthenticatedPheromoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/openclaw': {
      id: '/_authenticated/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof AuthenticatedOpenclawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/omega': {
      id: '/_authenticated/omega'
      path: '/omega'
      fullPath: '/omega'
      preLoaderRoute: typeof AuthenticatedOmegaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/obsidian': {
      id: '/_authenticated/obsidian'
      path: '/obsidian'
      fullPath: '/obsidian'
      preLoaderRoute: typeof AuthenticatedObsidianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observability': {
      id: '/_authenticated/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventor': {
      id: '/_authenticated/inventor'
      path: '/inventor'
      fullPath: '/inventor'
      preLoaderRoute: typeof AuthenticatedInventorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flywheel': {
      id: '/_authenticated/flywheel'
      path: '/flywheel'
      fullPath: '/flywheel'
      preLoaderRoute: typeof AuthenticatedFlywheelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet-learning': {
      id: '/_authenticated/fleet-learning'
      path: '/fleet-learning'
      fullPath: '/fleet-learning'
      preLoaderRoute: typeof AuthenticatedFleetLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engagement-workspace': {
      id: '/_authenticated/engagement-workspace'
      path: '/engagement-workspace'
      fullPath: '/engagement-workspace'
      preLoaderRoute: typeof AuthenticatedEngagementWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cron': {
      id: '/_authenticated/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AuthenticatedCronRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cognitive': {
      id: '/_authenticated/cognitive'
      path: '/cognitive'
      fullPath: '/cognitive'
      preLoaderRoute: typeof AuthenticatedCognitiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chains': {
      id: '/_authenticated/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof AuthenticatedChainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benchmark': {
      id: '/_authenticated/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof AuthenticatedBenchmarkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anomaly': {
      id: '/_authenticated/anomaly'
      path: '/anomaly'
      fullPath: '/anomaly'
      preLoaderRoute: typeof AuthenticatedAnomalyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adoption': {
      id: '/_authenticated/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AuthenticatedAdoptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/deliverable/draft': {
      id: '/_authenticated/deliverable/draft'
      path: '/deliverable/draft'
      fullPath: '/deliverable/draft'
      preLoaderRoute: typeof AuthenticatedDeliverableDraftRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/audit': {
      id: '/_authenticated/compliance/audit'
      path: '/compliance/audit'
      fullPath: '/compliance/audit'
      preLoaderRoute: typeof AuthenticatedComplianceAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdoptionRoute: typeof AuthenticatedAdoptionRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnomalyRoute: typeof AuthenticatedAnomalyRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBenchmarkRoute: typeof AuthenticatedBenchmarkRoute
  AuthenticatedChainsRoute: typeof AuthenticatedChainsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCognitiveRoute: typeof AuthenticatedCognitiveRoute
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedCronRoute: typeof AuthenticatedCronRoute
  AuthenticatedEngagementWorkspaceRoute: typeof AuthenticatedEngagementWorkspaceRoute
  AuthenticatedFleetLearningRoute: typeof AuthenticatedFleetLearningRoute
  AuthenticatedFlywheelRoute: typeof AuthenticatedFlywheelRoute
  AuthenticatedInventorRoute: typeof AuthenticatedInventorRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedObservabilityRoute: typeof AuthenticatedObservabilityRoute
  AuthenticatedObsidianRoute: typeof AuthenticatedObsidianRoute
  AuthenticatedOmegaRoute: typeof AuthenticatedOmegaRoute
  AuthenticatedOpenclawRoute: typeof AuthenticatedOpenclawRoute
  AuthenticatedPheromoneRoute: typeof AuthenticatedPheromoneRoute
  AuthenticatedProcessWorkspaceRoute: typeof AuthenticatedProcessWorkspaceRoute
  AuthenticatedProjectBoardRoute: typeof AuthenticatedProjectBoardRoute
  AuthenticatedProjectOverviewRoute: typeof AuthenticatedProjectOverviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComplianceAuditRoute: typeof AuthenticatedComplianceAuditRoute
  AuthenticatedDeliverableDraftRoute: typeof AuthenticatedDeliverableDraftRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdoptionRoute: AuthenticatedAdoptionRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnomalyRoute: AuthenticatedAnomalyRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBenchmarkRoute: AuthenticatedBenchmarkRoute,
  AuthenticatedChainsRoute: AuthenticatedChainsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCognitiveRoute: AuthenticatedCognitiveRoute,
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedCronRoute: AuthenticatedCronRoute,
  AuthenticatedEngagementWorkspaceRoute: AuthenticatedEngagementWorkspaceRoute,
  AuthenticatedFleetLearningRoute: AuthenticatedFleetLearningRoute,
  AuthenticatedFlywheelRoute: AuthenticatedFlywheelRoute,
  AuthenticatedInventorRoute: AuthenticatedInventorRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedObservabilityRoute: AuthenticatedObservabilityRoute,
  AuthenticatedObsidianRoute: AuthenticatedObsidianRoute,
  AuthenticatedOmegaRoute: AuthenticatedOmegaRoute,
  AuthenticatedOpenclawRoute: AuthenticatedOpenclawRoute,
  AuthenticatedPheromoneRoute: AuthenticatedPheromoneRoute,
  AuthenticatedProcessWorkspaceRoute: AuthenticatedProcessWorkspaceRoute,
  AuthenticatedProjectBoardRoute: AuthenticatedProjectBoardRoute,
  AuthenticatedProjectOverviewRoute: AuthenticatedProjectOverviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComplianceAuditRoute: AuthenticatedComplianceAuditRoute,
  AuthenticatedDeliverableDraftRoute: AuthenticatedDeliverableDraftRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
