#!/usr/bin/env bash
# SESSION CONTEXT INJECTOR — widgetdc-orchestrator
echo "═══ WIDGETDC ORCHESTRATOR — SESSION CONTEXT ═══"
echo ""
echo "CRITICAL RULES (ENFORCED):"
echo ""
echo "1. MCP ROUTE FORMAT: {\"tool\":\"name\",\"payload\":{...}}"
echo "   ALDRIG brug 'args' — altid 'payload'"
echo ""
echo "2. READ BEFORE WRITE"
echo "   ALDRIG opret nye filer under src/, routes/ uden først"
echo "   at læse mindst 2 eksisterende filer i mappen."
echo ""
echo "3. ESM only | Auth: Bearer API_KEY | dist/ committed"
echo ""
echo "4. Frontend: vanilla JS ONLY — ingen TypeScript syntax"
echo ""
echo "5. LESSON CHECK: Kald audit.lessons ved session boot."
echo "   POST /api/mcp/route {\"tool\":\"audit.lessons\",\"payload\":{\"agentId\":\"YOUR_ID\"}}"
echo ""
echo "6. AUTONOMI: Når bruger skriver '100% autonomt' — kør til opgaven er done."
echo ""
echo "═══ END INJECTION ═══"
